{{- if .Values.kibana.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.kibana.syncWave }}"
    
spec:
  project: default
  source:
    repoURL: 'https://github.com/norelnorel3/testing.git'
    path: kibana
    targetRevision: main
    helm:
      valueFiles:
        - values-copy.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  {{- if .Values.kibana.syncPolicy.enable }}
  syncPolicy:
    automated:
      prune: {{ .Values.kibana.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.kibana.syncPolicy.automated.selfHeal }}
  {{- end }}
    {{- if .Values.kibana.syncOptions.enable }}
    syncOptions:
      {{- range .Values.kibana.syncOptions.options }}
      - {{ . }}
      {{- end }}
    {{- end }}
{{- end }}